### ISSUE TITLE
docker command starts service 

### ISSUE THREAD

**Issue by madhavajay** [docker/desktop-linux#78]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Running the `docker` command should not start the docker service.
On Mac and Windows it doesnt.

### Actual behavior
On linux running the `docker` cli command forces the service to start. This means there is no way to easily check if docker is running or not without starting it.

On mac and windows:
`docker info` provides what you need plus makes it easy to tell if docker is running or not.

### Information

  - Linux distro: Ubuntu 20.04
  - Distro version: 20.04
  - Linux Github-CI-Linux-Ubuntu-20-VM-1 5.15.0-1017-azure #20~20.04.1-Ubuntu SMP Fri Aug 5 12:16:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  - Docker Desktop Version: 
Docker version 20.10.11, build dea9396

### Steps to reproduce the behavior

```
$ systemctl stop docker
$ docker info
```

  1. ...
  2. ...

**Comment by aiordache** [comment]
@thaJeztah should we move this to moby/moby?

**Comment by thaJeztah** [comment]
Looks like I missed the earlier "ping"; this is not a bug, but intentional. The docker engine's systemd setup provides "socket activation" (through the `docker.socket` systemd unit), which means that systemd starts the Docker Engine service if a process tries to connect to the docker socket when it's not running.

https://github.com/moby/moby/blob/v24.0.2/contrib/init/systemd/docker.service#L6-L9
https://github.com/moby/moby/blob/v24.0.2/contrib/init/systemd/docker.socket


- more details also in this ticket; https://github.com/docker/cli/issues/3780#issuecomment-1253639377

I'll close this one as this is not a bug, but feel free to continue the conversation.
